language: node_js
os: linux
dist: bionic

node_js:
  - "node"
  - "12"
  - "10"

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # to skip the tests
      script: skip
      deploy:
        provider: script
        cleanup: false
        on:
          branch: master
        script:
          - npx semantic-release

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - npm ci

notifications:
  email: false
  slack: exist-db:$SLACK_TOKEN
