language: node_js

node_js:
  - "node"
  - "10"
  - "8"
  - "6"

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

# I m not sure if this is helping
cache:
  directories:
    - "node_modules"

before_install:
  - npm prune

install:
  - npm install -q

notifications:
  email: false
