notifications:
  email: false

language: node_js

node_js:
  - "node"
  - "10"
  - "8"
  - "6"

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release

cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img
  - npm prune

install:
  - npm install -q
  - ant

before_script:
  - docker cp ./build/*-dev.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30
  - docker ps

script:
  - npm test
  <%_ if (apptype == 'exist-design' || 'plain') { %>- cypress run<% } -%>

  # - ant test

after_success:
  - docker stop exist-ci
