sudo: required
notifications:
  email: false

language: node_js

services:
  - docker

env:
  - IMG=duncdrum/exist-docker:latest
  - IMG=evolvedbinary/docker-existdb:eXist-4.3.0-minimal

# required if language is not java
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - "node_modules"

before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - docker pull $IMG
  - docker create  —name exist-ci -p 8080:8080 $IMG
  - npm prune

install:
  - npm install -q
  - ant

before_script:
  - docker cp ./build/*-dev.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30

script:
  - npm test
  # - ant test

after_success:
  - docker ps
  # check if installation threw error
  # navigate to app index.html
  # run xqsuite tests
